### ISSUE TITLE
Frequent Internal Errors

### ISSUE THREAD

**Issue by ghost** [JoelGodOfwar/MoreMobHeads#12]
### What behaviour is expected:
The plugin starts up after putting the .jar file in the plugins folder.

### What behaviour is observed:
```
Stack Trace:
java.nio.file.NoSuchFileException: plugins/MoreMobHeads/messages.yml
-> -> -> -> -> -> -> -> This line <- <- <- <- <- <- <- <-
[18:33:23 ERROR]: [MoreMobHeads] INTERNAL ERROR: Could not load old_messages.yml
java.io.FileNotFoundException: plugins/MoreMobHeads/old_messages.yml (No such file or directory)
[18:33:23 ERROR]: Error occurred while enabling MoreMobHeads v1.20_1.0.34 (Is it up to date?)
[18:33:23 INFO]: [MoreMobHeads] Disabling MoreMobHeads v1.20_1.0.34
[18:33:23 INFO]: [MoreMobHeads] MoreMobHeads v1.20_1.0.34 is Disabled
```

### Steps/models to reproduce:
Remove the MoreMobHeads folder if it exists.
Put MoreMobHeads v1.20_1.0.34 in the plugins folder
Restart the server
The plugin doesn't startup

Then you might manually create an empty text file called "old_messages.yml" and the plugin does start.

### Plugin list:
`ArmorStandEditor, BetterConcrete, Citizens, MoreMobHeads, Multiverse-Core, Quests, RapidLeafDecay, *SilenceMobs, VillagerWorkstationHighlights, WorldEdit`

### Bukkit/Spigot server version or Paper build number:
`This server is running Paper version git-Paper-416 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 581fb30)
`
### Anything else:
I would like to add that this plugin does not handle any errors or unexpected commands very well at all. For example, writing` /mmh display` throws an Internal Error. I don't think a well-coded program should behave like that. It's an issue of not catching errors and instead just defaulting to not handling them at all. I would appreciate just a tiny bit more testing and stability before putting out production versions.
The server operators also cannot use many commands by default, for example` /mmh customtrader` due to "missing permissions"... but I am the OP. I should have all the permissions by default.

**Comment by JoelGodOfwar** [comment]
Not sure why you didn't include the entire stacktrace, but 99% of exceptions should now be handled internally.
That's not how permissions work, not every OP should have access to commands that can lag the server, or do things the Admin would not want done by just anyone.
Anyways here is the dev-build that should solve your issue.
https://discord.com/channels/654087250665144321/662940711167066123/1205978925189038130
