### ISSUE TITLE
Mob head names are not completely configurable

### ISSUE THREAD

**Issue by ghost** [JoelGodOfwar/MoreMobHeads#14]
### Plugin list:
ArmorStandEditor, BetterConcrete, Citizens, GrimAC, JoinMessage, MoreMobHeads, Multiverse-Core, Quests, RapidLeafDecay, *SilenceMobs, SupplyDrop, VillagerWorkstationHighlights, WorldEdit, WorldGuard

### Bukkit/Spigot server version or Paper build number:
git-Paper-448 (MC: 1.20.4)

![grafik](https://github.com/JoelGodOfwar/MoreMobHeads/assets/76809077/ae6297eb-9058-4733-876b-4c87121fbe5e)

When configuring head names, it is not possible to change one of the parts of the name ("head") which is attached to every head dropped. "Head" is always added to the name of the head, which is not configurable.

**Comment by JoelGodOfwar** [comment]
Thank you for pointing this out, that bit of code was missed.
This issue is fixed and a new dev-build will be released on the discord server today.
All issues are handled on discord.gg/Fq9HQ2dmtd
