### ISSUE TITLE
Console spammed with logs with debug mode turned off

### ISSUE THREAD

**Issue by ghost** [JoelGodOfwar/MoreMobHeads#16]
My console is spammed with logs whenever I damage a mob, even when debug mode is turned off (both using the config and the command). I have not turned the debug mode on at any point.

<img width="472" alt="Screenshot 2024-03-25 at 8 05 48 PM" src="https://github.com/JoelGodOfwar/MoreMobHeads/assets/76809077/ad46e6db-80a2-43c8-a865-ceae23a7f305">
<img width="113" alt="Screenshot 2024-03-25 at 8 06 17 PM" src="https://github.com/JoelGodOfwar/MoreMobHeads/assets/76809077/eab8cd7a-c694-4266-8967-078fbb742692">

### Plugin list:
ArmorStandEditor, BetterConcrete, Citizens, GrimAC, JoinMessage, MoreMobHeads, Multiverse-Core, Quests, RapidLeafDecay, *SilenceMobs, SupplyDrop, VillagerWorkstationHighlights, WorldEdit, WorldGuard

### Bukkit/Spigot server version or Paper build number:
Paper-457 (MC: 1.20.4)

**Comment by JoelGodOfwar** [comment]
Thank you for finding that, it was supposed to be a debug log, but was a log log, it has now been fixed. I will release a fixed release version here in a few minutes.
