### ISSUE TITLE
Plugin does not work with 1.20.6

### ISSUE THREAD

**Issue by IasonKalaitzakis** [JoelGodOfwar/MoreMobHeads#20]
Hello, plugin does not work with 1.20.6. Any chance it will be updated? Thanks :)

**Comment by JoelGodOfwar** [comment]
Disable Custom wandering traders, and MMH works fine on Spigot 1.20.6, Paper and other forks of paper are not stable yet.

**Comment by IasonKalaitzakis** [comment]
> Disable Custom wandering traders, and MMH works fine on Spigot 1.20.6, Paper and other forks of paper are not stable yet.

Tried disabling custom wandering traders on the latest 1.20.6 paper build, plugin failed to load sadly. Is paper 1.20.6 considered stable by now?

**Comment by JoelGodOfwar** [comment]
The Custom wandering trader will take a complete rewrite, and still not sure if that will work.
The main plugin works fine, as long as you use dev build 1.20_1.0.38.D4 or D5 which stops the crashes from trying to load the trades for wandering trades. Both can be downloaded here https://discord.com/channels/654087250665144321/662940711167066123
