### ISSUE TITLE
Player memory leak

### ISSUE THREAD

**Issue by ChanceSD** [JoelGodOfwar/MoreMobHeads#22]
There's a memory leak of Player instances in chanceRandoms
![image](https://github.com/user-attachments/assets/5288707f-888a-475f-82ea-a18cda9fc207)
They remain there even after a player leaves the server. 
I was going to make a pull request fixing it but for some reason can't compile it and weirdly your latest commits also include no code.

Anyway, here's what I was going to do and should be enough to fix the issue.
```JAVA
	/**
	 * Removes player from map when they leave the server
	 */
	@EventHandler
	public void onPlayerQuit(PlayerQuitEvent event) {
		chanceRandoms.remove(event.getPlayer());
	}
```

**Comment by JoelGodOfwar** [comment]
Added suggestion. Thank you for pointing this out.

**Comment by ChanceSD** [comment]
Thank you. Any estimate on when you will upload the update with this?

**Comment by JoelGodOfwar** [comment]
https://discord.com/channels/654087250665144321/662940711167066123/1273376329588408385
